export const Industries = Object.freeze({
  BLANK: 'Choose an Industry',
  ADVERTISING: 'Advertising',
  AEROSPACE_DEFENSE: 'Aerospace/Defense',
  AIR_TRANSPORT: 'Air Transport',
  APPAREL: 'Apparel',
  AUTO_TRUCK: 'Auto & Truck',
  AUTO_PARTS: 'Auto Parts',
  BANK_MONEY_CENTER: 'Bank (Money Center)',
  BANKS_REGIONAL: 'Banks (Regional)',
  BEVERAGE_ALCOHOLIC: 'Beverage (Alcoholic)',
  BEVERAGE_SOFT: 'Beverage (Soft)',
  BROADCASTING: 'Broadcasting',
  BROKERAGE_INVESTMENT_BANKING: 'Brokerage & Investment Banking',
  BUILDING_MATERIALS: 'Building Materials',
  BUSINESS_CONSUMER_SERVICES: 'Business & Consumer Services',
  CABLE_TV: 'Cable TV',
  CHEMICAL_BASIC: 'Chemical (Basic)',
  CHEMICAL_DIVERSIFIED: 'Chemical (Diversified)',
  CHEMICAL_SPECIALTY: 'Chemical (Specialty)',
  COAL_RELATED_ENERGY: 'Coal & Related Energy',
  COMPUTER_SERVICES: 'Computer Services',
  COMPUTERS_PERIPHERALS: 'Computers/Peripherals',
  CONSTRUCTION_SUPPLIES: 'Construction Supplies',
  DIVERSIFIED: 'Diversified',
  DRUGS_BIOTECHNOLOGY: 'Drugs (Biotechnology)',
  DRUGS_PHARMACEUTICAL: 'Drugs (Pharmaceutical)',
  EDUCATION: 'Education',
  ELECTRICAL_EQUIPMENT: 'Electrical Equipment',
  ELECTRONICS_CONSUMER_OFFICE: 'Electronics (Consumer & Office)',
  ELECTRONICS_GENERAL: 'Electronics (General)',
  ENGINEERING_CONSTRUCTION: 'Engineering/Construction',
  ENTERTAINMENT: 'Entertainment',
  ENVIRONMENTAL_WASTE_SERVICES: 'Environmental & Waste Services',
  FARMING_AGRICULTURE: 'Farming/Agriculture',
  FINANCIAL_SVCS_NON_BANK_INSURANCE: 'Financial Svcs. (Non-bank & Insurance)',
  FOOD_PROCESSING: 'Food Processing',
  FOOD_WHOLESALERS: 'Food Wholesalers',
  FURN_HOME_FURNISHINGS: 'Furn/Home Furnishings',
  GREEN_RENEWABLE_ENERGY: 'Green & Renewable Energy',
  HEALTHCARE_PRODUCTS: 'Healthcare Products',
  HEALTHCARE_SUPPORT_SERVICES: 'Healthcare Support Services',
  HEATHCARE_INFORMATION_AND_TECHNOLOGY: 'Heathcare Information and Technology',
  HOMEBUILDING: 'Homebuilding',
  HOSPITALS_HEALTHCARE_FACILITIES: 'Hospitals/Healthcare Facilities',
  HOTEL_GAMING: 'Hotel/Gaming',
  HOUSEHOLD_PRODUCTS: 'Household Products',
  INFORMATION_SERVICES: 'Information Services',
  INSURANCE_GENERAL: 'Insurance (General)',
  INSURANCE_LIFE: 'Insurance (Life)',
  INSURANCE_PROP_CAS: 'Insurance (Prop/Cas.)',
  INVESTMENTS_ASSET_MANAGEMENT: 'Investments & Asset Management',
  MACHINERY: 'Machinery',
  METALS_MINING: 'Metals & Mining',
  OFFICE_EQUIPMENT_SERVICES: 'Office Equipment & Services',
  OIL_GAS_INTEGRATED: 'Oil/Gas (Integrated)',
  OIL_GAS_PRODUCTION_EXPLORATION: 'Oil/Gas (Production and Exploration)',
  OIL_GAS_DISTRIBUTION: 'Oil/Gas Distribution',
  OILFIELD_SVCS_EQUIP: 'Oilfield Svcs/Equip.',
  PACKAGING_CONTAINER: 'Packaging & Container',
  PAPER_FOREST_PRODUCTS: 'Paper/Forest Products',
  POWER: 'Power',
  PRECIOUS_METALS: 'Precious Metals',
  PUBLISHING_NEWSPAPERS: 'Publishing & Newspapers',
  REIT: 'R.E.I.T.',
  REAL_ESTATE_DEVELOPMENT: 'Real Estate (Development)',
  REAL_ESTATE_GENERAL_DIVERSIFIED: 'Real Estate (General/Diversified)',
  REAL_ESTATE_OPERATIONS_SERVICES: 'Real Estate (Operations & Services)',
  RECREATION: 'Recreation',
  REINSURANCE: 'Reinsurance',
  RESTAURANT_DINING: 'Restaurant/Dining',
  RETAIL_AUTOMOTIVE: 'Retail (Automotive)',
  RETAIL_BUILDING_SUPPLY: 'Retail (Building Supply)',
  RETAIL_DISTRIBUTORS: 'Retail (Distributors)',
  RETAIL_GENERAL: 'Retail (General)',
  RETAIL_GROCERY_AND_FOOD: 'Retail (Grocery and Food)',
  RETAIL_REITS: 'Retail (REITs)',
  RETAIL_SPECIAL_LINES: 'Retail (Special Lines)',
  RUBBER_TIRES: 'Rubber& Tires',
  SEMICONDUCTOR: 'Semiconductor',
  SEMICONDUCTOR_EQUIP: 'Semiconductor Equip',
  SHIPBUILDING_MARINE: 'Shipbuilding & Marine',
  SHOE: 'Shoe',
  SOFTWARE_ENTERTAINMENT: 'Software (Entertainment)',
  SOFTWARE_INTERNET: 'Software (Internet)',
  SOFTWARE_SYSTEM_APPLICATION: 'Software (System & Application)',
  STEEL: 'Steel',
  TELECOM_WIRELESS: 'Telecom (Wireless)',
  TELECOM_EQUIPMENT: 'Telecom. Equipment',
  TELECOM_SERVICES: 'Telecom. Services',
  TOBACCO: 'Tobacco',
  TRANSPORTATION: 'Transportation',
  TRANSPORTATION_RAILROADS: 'Transportation (Railroads)',
  TRUCKING: 'Trucking',
  UTILITY_GENERAL: 'Utility (General)',
  UTILITY_WATER: 'Utility (Water)',
});

export const Countries = Object.freeze({
  BLANK: 'Select a Country',
  ABU_DHABI: 'Abu Dhabi',
  ALBANIA: 'Albania',
  ALGERIA: 'Algeria',
  ANDORRA_PRINCIPALITY_OF: 'Andorra (Principality of)',
  ANGOLA: 'Angola',
  ANGUILLA: 'Anguilla',
  ANTIGUA_BARBUDA: 'Antigua & Barbuda',
  ARGENTINA: 'Argentina',
  ARMENIA: 'Armenia',
  ARUBA: 'Aruba',
  AUSTRALIA: 'Australia',
  AUSTRIA: 'Austria',
  AZERBAIJAN: 'Azerbaijan',
  BAHAMAS: 'Bahamas',
  BAHRAIN: 'Bahrain',
  BANGLADESH: 'Bangladesh',
  BARBADOS: 'Barbados',
  BELARUS: 'Belarus',
  BELGIUM: 'Belgium',
  BELIZE: 'Belize',
  BENIN: 'Benin',
  BERMUDA: 'Bermuda',
  BOLIVIA: 'Bolivia',
  BOSNIA_AND_HERZEGOVINA: 'Bosnia and Herzegovina',
  BOTSWANA: 'Botswana',
  BRAZIL: 'Brazil',
  BRITISH_VIRGIN_ISLANDS: 'British Virgin Islands',
  BRUNEI: 'Brunei',
  BULGARIA: 'Bulgaria',
  BURKINA_FASO: 'Burkina Faso',
  CAMBODIA: 'Cambodia',
  CAMEROON: 'Cameroon',
  CANADA: 'Canada',
  CAPE_VERDE: 'Cape Verde',
  CAYMAN_ISLANDS: 'Cayman Islands',
  CHANNEL_ISLANDS: 'Channel Islands',
  CHILE: 'Chile',
  CHINA: 'China',
  COLOMBIA: 'Colombia',
  CONGO_DEMOCRATIC_REPUBLIC_OF: 'Congo (Democratic Republic of)',
  CONGO_REPUBLIC_OF: 'Congo (Republic of)',
  COOK_ISLANDS: 'Cook Islands',
  COSTA_RICA: 'Costa Rica',
  CROATIA: 'Croatia',
  CUBA: 'Cuba',
  CURACAO: 'Curaçao',
  CYPRUS: 'Cyprus',
  CZECH_REPUBLIC: 'Czech Republic',
  DENMARK: 'Denmark',
  DOMINICAN_REPUBLIC: 'Dominican Republic',
  ECUADOR: 'Ecuador',
  EGYPT: 'Egypt',
  EL_SALVADOR: 'El Salvador',
  ESTONIA: 'Estonia',
  ETHIOPIA: 'Ethiopia',
  FALKLAND_ISLANDS: 'Falkland Islands',
  FIJI: 'Fiji',
  FINLAND: 'Finland',
  FRANCE: 'France',
  FRENCH_GUIANA: 'French Guiana',
  GABON: 'Gabon',
  GAMBIA: 'Gambia',
  GEORGIA: 'Georgia',
  GERMANY: 'Germany',
  GHANA: 'Ghana',
  GIBRALTAR: 'Gibraltar',
  GREECE: 'Greece',
  GREENLAND: 'Greenland',
  GUATEMALA: 'Guatemala',
  GUERNSEY_STATES_OF: 'Guernsey (States of)',
  GUINEA: 'Guinea',
  GUINEA_BISSAU: 'Guinea-Bissau',
  GUYANA: 'Guyana',
  HAITI: 'Haiti',
  HONDURAS: 'Honduras',
  HONG_KONG: 'Hong Kong',
  HUNGARY: 'Hungary',
  ICELAND: 'Iceland',
  INDIA: 'India',
  INDONESIA: 'Indonesia',
  IRAN: 'Iran',
  IRAQ: 'Iraq',
  IRELAND: 'Ireland',
  ISLE_OF_MAN: 'Isle of Man',
  ISRAEL: 'Israel',
  ITALY: 'Italy',
  IVORY_COAST: 'Ivory Coast',
  JAMAICA: 'Jamaica',
  JAPAN: 'Japan',
  JERSEY_STATES_OF: 'Jersey (States of)',
  JORDAN: 'Jordan',
  KAZAKHSTAN: 'Kazakhstan',
  KENYA: 'Kenya',
  KOREA_DPR: 'Korea, D.P.R.',
  KUWAIT: 'Kuwait',
  KYRGYZSTAN: 'Kyrgyzstan',
  LAOS: 'Laos',
  LATVIA: 'Latvia',
  LEBANON: 'Lebanon',
  LIBERIA: 'Liberia',
  LIBYA: 'Libya',
  LIECHTENSTEIN: 'Liechtenstein',
  LITHUANIA: 'Lithuania',
  LUXEMBOURG: 'Luxembourg',
  MACAU: 'Macau',
  MACEDONIA: 'Macedonia',
  MADAGASCAR: 'Madagascar',
  MALAWI: 'Malawi',
  MALAYSIA: 'Malaysia',
  MALDIVES: 'Maldives',
  MALI: 'Mali',
  MALTA: 'Malta',
  MARTINIQUE: 'Martinique',
  MAURITIUS: 'Mauritius',
  MEXICO: 'Mexico',
  MOLDOVA: 'Moldova',
  MONACO: 'Monaco',
  MONGOLIA: 'Mongolia',
  MONTENEGRO: 'Montenegro',
  MONTSERRAT: 'Montserrat',
  MOROCCO: 'Morocco',
  MOZAMBIQUE: 'Mozambique',
  MYANMAR: 'Myanmar',
  NAMIBIA: 'Namibia',
  NEPAL: 'Nepal',
  NETHERLANDS: 'Netherlands',
  NETHERLANDS_ANTILLES: 'Netherlands Antilles',
  NEW_ZEALAND: 'New Zealand',
  NICARAGUA: 'Nicaragua',
  NIGER: 'Niger',
  NIGERIA: 'Nigeria',
  NORWAY: 'Norway',
  OMAN: 'Oman',
  PAKISTAN: 'Pakistan',
  PALESTINIAN_AUTHORITY: 'Palestinian Authority',
  PANAMA: 'Panama',
  PAPUA_NEW_GUINEA: 'Papua New Guinea',
  PARAGUAY: 'Paraguay',
  PERU: 'Peru',
  PHILIPPINES: 'Philippines',
  POLAND: 'Poland',
  PORTUGAL: 'Portugal',
  QATAR: 'Qatar',
  RAS_AL_KHAIMAH_EMIRATE_OF: 'Ras Al Khaimah (Emirate of)',
  REUNION: 'Reunion',
  ROMANIA: 'Romania',
  RUSSIA: 'Russia',
  RWANDA: 'Rwanda',
  SAINT_LUCIA: 'Saint Lucia',
  SAUDI_ARABIA: 'Saudi Arabia',
  SENEGAL: 'Senegal',
  SERBIA: 'Serbia',
  SHARJAH: 'Sharjah',
  SIERRA_LEONE: 'Sierra Leone',
  SINGAPORE: 'Singapore',
  SLOVAKIA: 'Slovakia',
  SLOVENIA: 'Slovenia',
  SOLOMON_ISLANDS: 'Solomon Islands',
  SOMALIA: 'Somalia',
  SOUTH_AFRICA: 'South Africa',
  SOUTH_KOREA: 'South Korea',
  SPAIN: 'Spain',
  SRI_LANKA: 'Sri Lanka',
  ST_MAARTEN: 'St. Maarten',
  ST_VINCENT_GRENADINES: 'St. Vincent & the Grenadines',
  SUDAN: 'Sudan',
  SURINAME: 'Suriname',
  SWAZILAND: 'Swaziland',
  SWEDEN: 'Sweden',
  SWITZERLAND: 'Switzerland',
  SYRIA: 'Syria',
  TAIWAN: 'Taiwan',
  TAJIKISTAN: 'Tajikistan',
  TANZANIA: 'Tanzania',
  THAILAND: 'Thailand',
  TOGO: 'Togo',
  TRINIDAD_TOBAGO: 'Trinidad & Tobago',
  TUNISIA: 'Tunisia',
  TURKEY: 'Turkey',
  TURKS_CAICOS_ISLANDS: 'Turks & Caicos Islands',
  UGANDA: 'Uganda',
  UKRAINE: 'Ukraine',
  UNITED_ARAB_EMIRATES: 'United Arab Emirates',
  UNITED_KINGDOM: 'United Kingdom',
  UNITED_STATES: 'United States',
  URUGUAY: 'Uruguay',
  UZBEKISTAN: 'Uzbekistan',
  VENEZUELA: 'Venezuela',
  VIETNAM: 'Vietnam',
  YEMEN: 'Yemen',
  ZAMBIA: 'Zambia',
  ZIMBABWE: 'Zimbabwe',
});

export const Regions = Object.freeze({
  BLANK: 'Select a Region',
  AFRICA: 'Africa',
  ASIA: 'Asia',
  AUSTRALIA_NEW_ZEALAND: 'Australia & New Zealand',
  CARIBBEAN: 'Caribbean',
  CENTRAL_SOUTH_AMERICA: 'Central and South America',
  EASTERN_EUROPE: 'Eastern Europe',
  MIDDLE_EAST: 'Middle East',
  NORTH_AMERICA: 'North America',
  WESTERN_EUROPE: 'Western Europe',
  EMEA: 'EMEA',
  ROW: 'Rest of World',
});

export const CocApproaches = Object.freeze({
  DIRECT: 'Direct Input',
  AVERAGE: 'Industry Average',
  DETAILED: 'Detailed Approach',
});

export const BetaApproaches = Object.freeze({
  DIRECT: 'Direct Input',
  SINGLE: 'Single Business',
  MULTI: 'Multiple Businesses',
});

export const ErpApproaches = Object.freeze({
  DIRECT: 'Direct Input',
  COUNTRY: 'Country of Incorporation',
  COUNTRIES: 'Operating Countries',
  REGIONS: 'Operating Regions',
});

export const CodApproaches = Object.freeze({
  DIRECT: 'Direct Input',
  SYNTHETIC: 'Synthetic Credit Rating',
  ACTUAL: 'Actual Credit Rating',
});

export const CodCompanyTypes = Object.freeze({
  SAFE: 'Large and Safe Company',
  RISKY: 'Small and Risky Company',
});

export const DebtRatings = Object.freeze({
  BLANK: 'Select a Credit Rating',
  AAA: 'Aaa/AAA',
  AA: 'Aa2/AA',
  A_PLUS: 'A1/A+',
  A: 'A2/A',
  A_MINUS: 'A3/A-',
  BBB: 'Baa2/BBB',
  BB_PLUS: 'Ba1/BB+',
  BB: 'Ba2/BB',
  B_PLUS: 'B1/B+',
  B: 'B2/B',
  B_MINUS: 'B3/B-',
  C: 'C2/C',
  CC: 'Ca2/CC',
  CCC: 'Caa/CCC',
  D: 'D2/D',
});

export const YesNo = Object.freeze({
  YES: 'Yes',
  NO: 'No',
});
